const fs = require('fs');
const path = require('path');
const { defineConfig } = require('vite');

function resolveConsumerRoot() {
  return process.cwd()
    .replace('/node_modules/vanilla-jet', '')
    .replace('/.scripts', '')
    .replace('/.grunt', '');
}

function collectScriptFiles(dirPath) {
  if (!fs.existsSync(dirPath)) {
    return [];
  }

  const files = [];
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  entries.forEach((entry) => {
    const entryPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectScriptFiles(entryPath));
      return;
    }

    if (entry.isFile() && entry.name.endsWith('.js')) {
      files.push(entryPath);
    }
  });
  return files;
}

function normalize(filePath) {
  return filePath.split(path.sep).join('/');
}

function scriptPriority(filePath) {
  const normalized = normalize(filePath);
  if (normalized.includes('/assets/scripts/controllers/')) return 0;
  if (normalized.includes('/assets/scripts/views/')) return 1;
  if (normalized.includes('/assets/scripts/api/')) return 2;
  return 3;
}

function includeInBundle(filePath) {
  const normalized = normalize(filePath);
  if (normalized.includes('/assets/scripts/core/')) return false;
  if (normalized.includes('/assets/scripts/plugins/')) return false;
  return true;
}

function writeVirtualEntry(virtualEntryPath, orderedScripts, lessEntryPath, hasLess) {
  const imports = orderedScripts.map((scriptPath, index) => {
    const importPath = normalize(scriptPath) + '?raw';
    return `import __vanillajet_script_${index} from ${JSON.stringify(importPath)};`;
  });

  if (hasLess) {
    imports.push(`import ${JSON.stringify(normalize(lessEntryPath))};`);
  }

  const mappings = orderedScripts.map((scriptPath, index) => {
    const rel = normalize(path.relative(path.dirname(virtualEntryPath), scriptPath));
    return `{ source: __vanillajet_script_${index}, file: ${JSON.stringify(rel)} }`;
  });

  const lines = [
    '/* Auto-generated by VanillaJet Vite config. */',
    ...imports,
    '',
    'function executeGlobalScript(sourceCode, sourceFile) {',
    '  const tag = document.createElement("script");',
    '  tag.type = "text/javascript";',
    '  tag.setAttribute("data-vanillajet-source", sourceFile);',
    '  tag.text = sourceCode;',
    '  document.head.appendChild(tag);',
    '  document.head.removeChild(tag);',
    '}',
    '',
    `const scriptMap = [${mappings.join(', ')}];`,
    'scriptMap.forEach(({ source, file }) => executeGlobalScript(source, file));',
    '',
    'if (import.meta.hot) {',
    '  import.meta.hot.accept(() => {',
    '    window.location.reload();',
    '  });',
    '}'
  ];

  fs.mkdirSync(path.dirname(virtualEntryPath), { recursive: true });
  fs.writeFileSync(virtualEntryPath, lines.join('\n'), 'utf8');
}

module.exports = defineConfig(({ command, mode }) => {
  const rootDir = resolveConsumerRoot();
  const scriptsDir = path.join(rootDir, 'assets/scripts');
  const lessEntryPath = path.join(rootDir, 'assets/styles/less/admin.less');
  const virtualEntryPath = path.join(rootDir, '.vanillajet/vite-entry.js');

  const scripts = collectScriptFiles(scriptsDir)
    .filter(includeInBundle)
    .sort((left, right) => {
      const priorityDiff = scriptPriority(left) - scriptPriority(right);
      if (priorityDiff !== 0) {
        return priorityDiff;
      }
      return normalize(left).localeCompare(normalize(right));
    });
  const hasLess = fs.existsSync(lessEntryPath);
  const hasSources = scripts.length > 0 || hasLess;

  writeVirtualEntry(virtualEntryPath, scripts, lessEntryPath, hasLess);

  const helperPath = '/__vanillajet__/';
  const helperHtml = [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    '  <title>VanillaJet Vite Dev</title>',
    '</head>',
    '<body>',
    '  <h3>VanillaJet Vite dev helper</h3>',
    '  <p>This page only loads JS/LESS from assets for DX.</p>',
    '  <p>Nunjucks templates and legacy Node routes remain unchanged.</p>',
    `  <script type="module" src="${normalize(path.relative(rootDir, virtualEntryPath)).startsWith('.') ? '/' + normalize(path.relative(rootDir, virtualEntryPath)).replace(/^\.\//, '') : '/' + normalize(path.relative(rootDir, virtualEntryPath))}"></script>`,
    '</body>',
    '</html>'
  ].join('\n');

  return {
    root: rootDir,
    publicDir: false,
    server: {
      host: true,
      port: 5173
    },
    build: {
      outDir: path.join(rootDir, 'public'),
      emptyOutDir: false,
      sourcemap: mode !== 'production',
      rollupOptions: {
        input: virtualEntryPath,
        output: {
          entryFileNames: 'scripts/vanilla.min.js',
          chunkFileNames: 'scripts/chunks/[name]-[hash].js',
          assetFileNames: (assetInfo) => {
            if (assetInfo.name && assetInfo.name.endsWith('.css')) {
              return 'styles/app.min.css';
            }
            return 'assets/[name]-[hash][extname]';
          }
        }
      }
    },
    plugins: [
      {
        name: 'vanillajet-dev-helper',
        configureServer(server) {
          if (!hasSources) {
            server.config.logger.warn(
              '[vanillajet] No JS/LESS sources found under assets/. Vite will run with an empty entry.'
            );
          }

          server.middlewares.use((req, res, next) => {
            if (req.url === helperPath) {
              res.setHeader('Content-Type', 'text/html; charset=utf-8');
              res.end(helperHtml);
              return;
            }
            next();
          });
        },
        buildStart() {
          if (command === 'build' && !hasSources) {
            this.warn('[vanillajet] No JS/LESS sources found under assets/. Build will output an empty JS bundle.');
          }
        }
      }
    ]
  };
});
